### ISSUE TITLE
Great work! Helped creating sota embeddings

### ISSUE THREAD

**Issue by Muennighoff** [luyug/GradCache#10]
Just wanted to thank you for your great work! I used GradCache to build state of the art sentence embeddings (https://arxiv.org/abs/2202.08904). Thanks to GradCache, I could scale up batch sizes from 48 to 1024 for the model trained on NLI improving its average performance on USEB by 4%~

**Comment by frytoli** [comment]
I wanted to add on to this -- I was really hitting a wall trying to do SimCLR training for image embeddings on a single GPU, and this project *was* the solution. And, it was easy to plug-in to my existing code. Thank you!
