### ISSUE TITLE
TypeError at grad_cache/functional.py:39

### ISSUE THREAD

**Issue by syoungbaak** [luyug/GradCache#12]
I tried to follow your example in the functional approach.

But, I got the following TypeError.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [102], in <cell line: 1>()
      1 for f, r in zip(closures_x, cache_x):
----> 2     f(r)

File ~/git/GradCache/src/grad_cache/functional.py:39, in cached.<locals>.cache_func.<locals>.forward_backward_func(cache_reps)
     36     cache_reps = (cache_reps,)
     37 assert len(reps) == len(cache_reps)
---> 39 surrogate = sum(map(lambda u, v: torch.dot(u.flatten(), v.grad.flatten()), zip(reps, cache_reps)), 0)
     40 surrogate.backward()

TypeError: <lambda>() missing 1 required positional argument: 'v'

Is it right to change the 39th line as like this ?
surrogate = sum(map(lambda u, v: torch.dot(u.flatten(), v.grad.flatten()), reps, cache_reps), 0)

**Comment by luyug** [comment]
Thanks for catching that. 

> Is it right to change the 39th line as like this ?
surrogate = sum(map(lambda u, v: torch.dot(u.flatten(), v.grad.flatten()), reps, cache_reps), 0)

That's correct. I guess was confused between `map` and `starmap`.

**Comment by nforest** [comment]
Hi there,
I encounted the same error today, could you help fix the bug in the main branch? or I can send a PR fix if you wish.

Thanks!

**Comment by luyug** [comment]
Hi @nforest I have pushed a fix to main.

As a side note, PRs are very welcome! (This one is very simple so I figure no need to bother..)

**Comment by nforest** [comment]
Thanks a lot!
