### ISSUE TITLE
Compatibility with Huggingface Trainer

### ISSUE THREAD

**Issue by sh0416** [luyug/GradCache#2]
Hi,

First, congratulation of your nice and clear work.

I just wonder this code could be used with huggingface trainer.

I think it is bit tricky..

Thanks!

**Comment by luyug** [comment]
It should work (as long as you stay with Pytorch.)

In my works, I sub-class Trainer and override `__init__` and `training_step`.

**Comment by sh0416** [comment]
Thanks for the reply :)
I will try that approach.
