### ISSUE TITLE
Requirements of the python env?

### ISSUE THREAD

**Issue by MicPie** [luyug/GradCache#4]
Hi Luyu,

thank you very much for the very nice and clean repository! :-)

I was playing with GradCache to get it working with a CLIP setup and I needed some trail and error to find the right python version. With 3.6 `from contextlib import nullcontext` didn't work but with 3.8 I was able to get it to run. 

Therefore, I just wanted to ask you, if you have more information on your development environment, e.g., python version, etc., so I can compare it to mine.

Kind regards
Michael

**Comment by luyug** [comment]
I have run with python 3.8.x and 3.9.x and they both worked fine.

As a rule of thumb, you should get a working environment if you use conda to install the latest release of pytorch.
